### ISSUE TITLE
Setting the authentication parameters is not working

### ISSUE THREAD

**Issue by nomisssB** [willguibr/zpacloud-ansible#42]
### Summary

How do I need to pass the authentication parameters for the playbooks to work?
The documentation states to use the CLI or a seperate file: [https://github.com/willguibr/zpacloud-playbooks#customize-connection-parameters](https://github.com/willguibr/zpacloud-playbooks#customize-connection-parameters)
I tried passing them with the CLI, but it doesn't work:
`ansible-playbook --extra-vars "client_id=xxxxxxxxxxxx== client_secret=xxxxxxxxxx customer_id=xxxxxxxxxx" -vvv zpa_app_connector_groups_info.yml`
or
`ansible-playbook --extra-vars "zpa_client_id=xxxxxxxxxxxx== zpa_client_secret=xxxxxxxxxx zpa_customer_id=xxxxxxxxxx" -vvv zpa_app_connector_groups_info.yml`

The exception is always the same with the vars all being null:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/modules/zpa_app_connector_groups_info.py", line 108, in main
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/modules/zpa_app_connector_groups_info.py", line 79, in core
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/module_utils/zpa_client.py", line 136, in __init__
    response = self.login()
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/module_utils/zpa_client.py", line 42, in wrapper
    raise Exception("Reached max retries: %s" % (resp.json))
Exception: Reached max retries: {'id': 'invalid_client', 'reason': 'Client authentication failed.'}
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "client_id": null,
            "client_secret": null,
            "customer_id": null,
            "id": null,
            "name": null
        }
    },
    "msg": "Reached max retries: {'id': 'invalid_client', 'reason': 'Client authentication failed.'}"
}
```

I also tried to create zpa_cloud.yml and set the there:
```
vars:
        zpa_client_id: xxxxxxxxxxx
        zpa_client_secret: xxxxxxxxxxxx
        zpa_customer_id: xxxxxxxxx
```
or 
```
zpa_cloud:
		vars:
				zpa_client_id: xxxxxxxxxxx
				zpa_client_secret: xxxxxxxxxxxx
				zpa_customer_id: xxxxxxxxx
```

And finally to set environment variables:
```
(ansibleTest) xxxxxxx@xxxxxxxxxxxx:~> export | grep zpa
declare -x zpa_client_id="xxxxxxxxxxxxxxxxx"
declare -x zpa_client_secret="xxxxxxxxxxxxxxx"
declare -x zpa_customer_id="xxxxxxxxxxxxxxx"
```
I also tested it without zpa in front (e.g. just client_id), same result

The exception is always the same with the vars all being null:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/modules/zpa_app_connector_groups_info.py", line 108, in main
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/modules/zpa_app_connector_groups_info.py", line 79, in core
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/module_utils/zpa_client.py", line 136, in __init__
    response = self.login()
  File "/tmp/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload_y0slruer/ansible_willguibr.zpacloud.zpa_app_connector_groups_info_payload.zip/ansible_collections/willguibr/zpacloud/plugins/module_utils/zpa_client.py", line 42, in wrapper
    raise Exception("Reached max retries: %s" % (resp.json))
Exception: Reached max retries: {'id': 'invalid_client', 'reason': 'Client authentication failed.'}
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "client_id": null,
            "client_secret": null,
            "customer_id": null,
            "id": null,
            "name": null
        }
    },
    "msg": "Reached max retries: {'id': 'invalid_client', 'reason': 'Client authentication failed.'}"
}
```

### Issue Type

Documentation Report

### Component Name

authentication / test of zpa_app_connector_groups_info.yml

### Ansible Version

```console (paste below)
(ansibleTest) xxxxxxxxxxxx@xxxxxxxxxxxxxx:~/zpacloud-playbooks> ansible --version
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/home/ishome/xxxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/miniconda3/envs/ansibleTest/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ishome/xxxxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/miniconda3/envs/ansibleTest/bin/ansible
  python version = 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
  jinja version = 3.1.2
  libyaml = True
```

### willguibr.zpacloud Version

```console (paste below)
$ ansible-galaxy collection list willguibr.zpacloud
# /home/xxxxxxxxx/xxxxxxxx/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
willguibr.zpacloud 1.1.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
empty
```

### OS / Environment

```
$ uname -a
Linux xxxxxxxxxxxxx4.12.14-122.106-default #1 SMP Mon Jan 3 22:02:42 UTC 2022 (cca30be) x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles_sap:12:sp5"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by greg-hydrogen** [comment]
@nomisssB  - I had the same problem but I had fixed it my making the environment variables uppercase so they are all

export ZPA_CLIENT_ID=
export ZPA_CUSTOMER_ID=
export ZPA_CLIENT_SECRET=

in the shell and that worked, I can't get it to work from a file though, I am very new to this so it is likely something I am missing

**Comment by watsonb** [comment]
You can also define them inside your playbook like this:

```yaml
- name: My ZPA Playbook
  hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: local
    zpa_client_id: foo
    zpa_client_secret: bar
    zpa_customer_id: baz
  tasks:

    - name: Gather Details of All zpa_idp_controller_info
      willguibr.zpacloud.zpa_idp_controller_info:
        client_id: "{{ zpa_client_id }}"
        client_secret: "{{ zpa_client_secret }}"
        customer_id: "{{ zpa_customer_id }}"
      register: zpa_idp_controller_info
```

Of course, the actual name of the variables at the top of the playbook is up to you.  This also means you could define them in some inventory construct as well and pass them in as group/host vars.

**Comment by nomisssB** [comment]
@watsonb @greg-hydrogen Thanks for the help! I'm currently testing another solution but if I get back to Ansible I will try these.
